In [12]:
import numpy as np
import torch

In [108]:
#T, L, C = 64, 16, 4
T, L, C, D = 16, 4, 4, 10
A = np.zeros((L*L, C, T ))
for i in range(L):
    for j in range(i, L):
        window_id = i*L + j
        window_size = (j-i)+1
        # How to deal with the case where L does not divide T?
        window_start, num_frames = i*(T//L), window_size*(T//L)
        clip_size = 1
        if num_frames > C:
            clip_size = num_frames//C
        for c in range(min(C, num_frames)):
            clip_start = window_start + c*clip_size
            A[window_id, c, clip_start : clip_start + clip_size] = 1
print(A)

[[[1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 1. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 0. 0. 1.]]]


In [52]:
x = np.random.rand(T, D)
print(x)
fc = A@x

[[0.81926997 0.8135186  0.09411669 0.94408148 0.67250249 0.8698904
  0.46948144 0.083385   0.11338153 0.08112357]
 [0.05727078 0.90695298 0.94004252 0.65732195 0.85983149 0.92427571
  0.74357695 0.81329758 0.55317541 0.33750069]
 [0.96532088 0.67363184 0.70843297 0.57115087 0.32199964 0.20394811
  0.85713507 0.36725894 0.32618928 0.89727007]
 [0.43706667 0.89590377 0.62848275 0.42672005 0.37472572 0.82242285
  0.52380917 0.24091916 0.77973524 0.92488184]
 [0.83043178 0.64806025 0.04667917 0.88833918 0.63114961 0.08260198
  0.14776807 0.89776749 0.95344625 0.84070554]
 [0.77560566 0.144255   0.85493605 0.17153244 0.38597401 0.01555488
  0.79572826 0.94116808 0.87738221 0.72710209]
 [0.31384815 0.36152698 0.18020528 0.96822501 0.32047326 0.14980431
  0.06384822 0.12067631 0.55932163 0.01523369]
 [0.59775169 0.77660131 0.54110542 0.64614511 0.40807428 0.17991207
  0.85143841 0.35676625 0.36633005 0.71456633]
 [0.25616425 0.75260572 0.57018906 0.51453102 0.93183385 0.96406972
  0.89493858 

In [53]:
fc

array([[[0.81926997, 0.8135186 , 0.09411669, 0.94408148, 0.67250249,
         0.8698904 , 0.46948144, 0.083385  , 0.11338153, 0.08112357],
        [0.05727078, 0.90695298, 0.94004252, 0.65732195, 0.85983149,
         0.92427571, 0.74357695, 0.81329758, 0.55317541, 0.33750069],
        [0.96532088, 0.67363184, 0.70843297, 0.57115087, 0.32199964,
         0.20394811, 0.85713507, 0.36725894, 0.32618928, 0.89727007],
        [0.43706667, 0.89590377, 0.62848275, 0.42672005, 0.37472572,
         0.82242285, 0.52380917, 0.24091916, 0.77973524, 0.92488184]],

       [[0.87654076, 1.72047158, 1.03415921, 1.60140343, 1.53233398,
         1.79416611, 1.21305838, 0.89668259, 0.66655694, 0.41862426],
        [1.40238755, 1.56953561, 1.33691572, 0.99787092, 0.69672536,
         1.02637095, 1.38094424, 0.6081781 , 1.10592451, 1.82215191],
        [1.60603744, 0.79231525, 0.90161522, 1.05987162, 1.01712363,
         0.09815686, 0.94349633, 1.83893557, 1.83082846, 1.56780763],
        [0.91159984, 1.13

In [54]:
y = np.random.rand(5, 4, 4)

In [55]:
print(y)

[[[0.37993152 0.54999981 0.42093912 0.7460686 ]
  [0.74957943 0.13714517 0.66024172 0.23662413]
  [0.05387628 0.95602864 0.16687586 0.80180003]
  [0.25795593 0.51075786 0.52005241 0.24228914]]

 [[0.25402297 0.3541268  0.3759863  0.77238539]
  [0.19746212 0.72198826 0.39909138 0.30423825]
  [0.38820546 0.35047099 0.4620726  0.05560755]
  [0.52704558 0.94598523 0.25639945 0.27577749]]

 [[0.9131838  0.16740282 0.61471636 0.52284307]
  [0.40286423 0.86781476 0.05510229 0.30166997]
  [0.92031744 0.92041462 0.76890681 0.86249004]
  [0.2501879  0.97952952 0.20331295 0.42497613]]

 [[0.377539   0.03763133 0.35074961 0.27922304]
  [0.13976362 0.11369861 0.83349588 0.15270401]
  [0.90901063 0.33456491 0.96781346 0.91272586]
  [0.72156375 0.48494191 0.65186549 0.0270488 ]]

 [[0.00482084 0.95493557 0.68336002 0.35924914]
  [0.73747208 0.85017076 0.33151239 0.54076535]
  [0.3830995  0.35538467 0.47503574 0.38684458]
  [0.95641045 0.3323867  0.53307096 0.57130734]]]


In [56]:
z = y.reshape(5, 2, 2, 4)

In [57]:
print(z)

[[[[0.37993152 0.54999981 0.42093912 0.7460686 ]
   [0.74957943 0.13714517 0.66024172 0.23662413]]

  [[0.05387628 0.95602864 0.16687586 0.80180003]
   [0.25795593 0.51075786 0.52005241 0.24228914]]]


 [[[0.25402297 0.3541268  0.3759863  0.77238539]
   [0.19746212 0.72198826 0.39909138 0.30423825]]

  [[0.38820546 0.35047099 0.4620726  0.05560755]
   [0.52704558 0.94598523 0.25639945 0.27577749]]]


 [[[0.9131838  0.16740282 0.61471636 0.52284307]
   [0.40286423 0.86781476 0.05510229 0.30166997]]

  [[0.92031744 0.92041462 0.76890681 0.86249004]
   [0.2501879  0.97952952 0.20331295 0.42497613]]]


 [[[0.377539   0.03763133 0.35074961 0.27922304]
   [0.13976362 0.11369861 0.83349588 0.15270401]]

  [[0.90901063 0.33456491 0.96781346 0.91272586]
   [0.72156375 0.48494191 0.65186549 0.0270488 ]]]


 [[[0.00482084 0.95493557 0.68336002 0.35924914]
   [0.73747208 0.85017076 0.33151239 0.54076535]]

  [[0.3830995  0.35538467 0.47503574 0.38684458]
   [0.95641045 0.3323867  0.53307096 0.5713

In [58]:
B = A.reshape(L, L, C, T)
print(B[0,:,:,:])

[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]]


In [59]:
C = A.transpose(1, 0, 2)
print(C.shape)

(4, 16, 16)


In [60]:
print(C[3,:, :])

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [61]:
bx = np.random.rand(2, T, D)

In [62]:
C@bx

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,16,16)->(4,newaxis,newaxis) (2,16,10)->(2,newaxis,newaxis)  and requested shape (16,10)

In [95]:
a = np.random.rand(L, L, C, T)
b = np.ones((2, T, D))

In [97]:
c = np.einsum('lmik, bkj -> blmij', a, b)

In [98]:
print(c.shape)

(2, 4, 4, 4, 10)


In [99]:
print(c)

[[[[[ 6.68174166  6.68174166  6.68174166 ...  6.68174166  6.68174166
      6.68174166]
    [ 8.97805021  8.97805021  8.97805021 ...  8.97805021  8.97805021
      8.97805021]
    [ 6.56637436  6.56637436  6.56637436 ...  6.56637436  6.56637436
      6.56637436]
    [ 7.16685601  7.16685601  7.16685601 ...  7.16685601  7.16685601
      7.16685601]]

   [[ 6.70649768  6.70649768  6.70649768 ...  6.70649768  6.70649768
      6.70649768]
    [ 7.78991664  7.78991664  7.78991664 ...  7.78991664  7.78991664
      7.78991664]
    [ 6.99692755  6.99692755  6.99692755 ...  6.99692755  6.99692755
      6.99692755]
    [ 8.94367808  8.94367808  8.94367808 ...  8.94367808  8.94367808
      8.94367808]]

   [[ 8.23980562  8.23980562  8.23980562 ...  8.23980562  8.23980562
      8.23980562]
    [ 9.44437945  9.44437945  9.44437945 ...  9.44437945  9.44437945
      9.44437945]
    [ 6.545526    6.545526    6.545526   ...  6.545526    6.545526
      6.545526  ]
    [ 8.56539647  8.56539647  8.56539647 

In [100]:
d = np.array([a@b[0], a@b[1]])

In [101]:
print(d)

[[[[[ 6.68174166  6.68174166  6.68174166 ...  6.68174166  6.68174166
      6.68174166]
    [ 8.97805021  8.97805021  8.97805021 ...  8.97805021  8.97805021
      8.97805021]
    [ 6.56637436  6.56637436  6.56637436 ...  6.56637436  6.56637436
      6.56637436]
    [ 7.16685601  7.16685601  7.16685601 ...  7.16685601  7.16685601
      7.16685601]]

   [[ 6.70649768  6.70649768  6.70649768 ...  6.70649768  6.70649768
      6.70649768]
    [ 7.78991664  7.78991664  7.78991664 ...  7.78991664  7.78991664
      7.78991664]
    [ 6.99692755  6.99692755  6.99692755 ...  6.99692755  6.99692755
      6.99692755]
    [ 8.94367808  8.94367808  8.94367808 ...  8.94367808  8.94367808
      8.94367808]]

   [[ 8.23980562  8.23980562  8.23980562 ...  8.23980562  8.23980562
      8.23980562]
    [ 9.44437945  9.44437945  9.44437945 ...  9.44437945  9.44437945
      9.44437945]
    [ 6.545526    6.545526    6.545526   ...  6.545526    6.545526
      6.545526  ]
    [ 8.56539647  8.56539647  8.56539647 

In [94]:
c-d

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0.

In [159]:
def compute_content_matrix(T, L, C):
    X = np.zeros((L, L, C, T))
    for i in range(L):
        for j in range(i, L):
            window_size = (j-i)+1
            # How to deal with the case where L does not divide T?
            window_start, num_frames = i*(T//L), window_size*(T//L)
            clip_size = 1
            if num_frames > C:
                clip_size = num_frames//C
            for c in range(min(C, num_frames)):
                clip_start = window_start + c*clip_size
                X[i, j, c, clip_start : clip_start + clip_size] = 1
    return X

In [162]:
T, L, C, D = 16, 4, 4, 10
R = compute_content_matrix(T,L,C)
print(R.shape)

(4, 4, 4, 16)


In [161]:
R

array([[[[1., 0., 0., ..., 0., 0., 0.],
         [0., 1., 0., ..., 0., 0., 0.],
         [0., 0., 1., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[1., 1., 0., ..., 0., 0., 0.],
         [0., 0., 1., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 1., 1., 1.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ...,

In [109]:
S = A.reshape(L,L,C,T)

In [111]:
np.sum(R-S)

0.0

In [166]:
# How to deal with the case where L does not divide T?
def compute_content_matrix(T, L, C):
    X = torch.zeros((L, L, C, T))
    for i in range(L):
        for j in range(i, L):
            window_size = (j-i)+1
            window_start, num_frames = i*(T//L), window_size*(T//L)
            clip_size = 1
            if num_frames > C:
                clip_size = num_frames//C
            for c in range(min(C, num_frames)):
                clip_start = window_start + c*clip_size
                X[i, j, c, clip_start : clip_start + clip_size] = 1
    return X

In [168]:

R = compute_content_matrix(T,L,C)
print(R[0,:, :, :])

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0

In [170]:
print(R.shape)
print(R[0,:,:,:])

torch.Size([4, 4, 4, 16])
tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [151]:
#x = torch.ones(2, T, D)
x = torch.ones((2, T, D))
c = torch.einsum('lmit, btj -> blmij', R, x)
print(c.shape)

torch.Size([2, 4, 4, 4, 10])


In [152]:
print(c)
print(c.shape)

tensor([[[[[1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.]],

          [[2., 2., 2.,  ..., 2., 2., 2.],
           [2., 2., 2.,  ..., 2., 2., 2.],
           [2., 2., 2.,  ..., 2., 2., 2.],
           [2., 2., 2.,  ..., 2., 2., 2.]],

          [[3., 3., 3.,  ..., 3., 3., 3.],
           [3., 3., 3.,  ..., 3., 3., 3.],
           [3., 3., 3.,  ..., 3., 3., 3.],
           [3., 3., 3.,  ..., 3., 3., 3.]],

          [[4., 4., 4.,  ..., 4., 4., 4.],
           [4., 4., 4.,  ..., 4., 4., 4.],
           [4., 4., 4.,  ..., 4., 4., 4.],
           [4., 4., 4.,  ..., 4., 4., 4.]]],


         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],

          [[1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],

In [150]:
c = np.einsum('lmit, btj -> blmij', R, x)


In [173]:
print(R.shape)
torch.sum(R, dim=2)

torch.Size([4, 4, 4, 16])


tensor([[[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0

In [174]:
R[0,:,:,:]

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0

In [197]:
x = torch.rand(2, T, D)
print(x.shape)

torch.Size([2, 16, 10])


In [198]:
y = torch.permute(x, (0, 2, 1))
print(y)

tensor([[[0.1561, 0.3907, 0.2147, 0.1108, 0.4733, 0.0726, 0.2664, 0.4985,
          0.0202, 0.1417, 0.5238, 0.6082, 0.0899, 0.2835, 0.9644, 0.8525],
         [0.4837, 0.2085, 0.3240, 0.9815, 0.6460, 0.9105, 0.6702, 0.0250,
          0.8475, 0.0502, 0.5375, 0.9910, 0.0266, 0.4491, 0.3124, 0.4379],
         [0.3337, 0.6097, 0.1396, 0.5996, 0.8426, 0.2437, 0.0392, 0.1814,
          0.6267, 0.0594, 0.5842, 0.3950, 0.5648, 0.1319, 0.4026, 0.4922],
         [0.7233, 0.7925, 0.0430, 0.7500, 0.8331, 0.8886, 0.3659, 0.8498,
          0.7425, 0.1756, 0.9730, 0.2452, 0.3095, 0.9666, 0.4308, 0.0914],
         [0.8813, 0.0352, 0.6729, 0.0203, 0.3980, 0.5771, 0.7079, 0.9859,
          0.2174, 0.1331, 0.2131, 0.4748, 0.2633, 0.2610, 0.7987, 0.6528],
         [0.3078, 0.4751, 0.4606, 0.9462, 0.6293, 0.7395, 0.1618, 0.3186,
          0.0626, 0.7886, 0.9798, 0.8367, 0.2541, 0.9607, 0.7683, 0.6906],
         [0.7481, 0.0931, 0.0414, 0.6444, 0.7341, 0.4902, 0.3192, 0.4121,
          0.4625, 0.2444, 0.6053

In [199]:
layer = torch.nn.AvgPool1d(T//L, stride=T//L)
z = layer(y)
print(z)

tensor([[[0.2181, 0.3277, 0.3235, 0.5476],
         [0.4994, 0.5629, 0.6066, 0.3065],
         [0.4207, 0.3267, 0.4163, 0.3979],
         [0.5772, 0.7343, 0.5341, 0.4496],
         [0.4024, 0.6672, 0.2596, 0.4939],
         [0.5474, 0.4623, 0.6669, 0.6684],
         [0.3817, 0.4889, 0.4612, 0.3576],
         [0.1296, 0.4807, 0.4372, 0.5724],
         [0.7456, 0.4263, 0.7643, 0.2986],
         [0.3540, 0.5792, 0.3312, 0.5567]],

        [[0.7605, 0.4321, 0.4624, 0.6031],
         [0.4339, 0.5861, 0.2525, 0.5530],
         [0.3442, 0.2328, 0.6226, 0.7344],
         [0.5792, 0.5398, 0.6313, 0.6788],
         [0.3153, 0.2913, 0.3271, 0.3344],
         [0.7892, 0.4234, 0.3057, 0.4077],
         [0.4327, 0.4183, 0.5653, 0.6090],
         [0.3710, 0.3687, 0.4519, 0.5592],
         [0.6724, 0.6235, 0.5837, 0.5442],
         [0.5369, 0.5549, 0.3911, 0.2665]]])


In [200]:
r = torch.permute(z, (0, 2, 1))
print(r)

tensor([[[0.2181, 0.4994, 0.4207, 0.5772, 0.4024, 0.5474, 0.3817, 0.1296,
          0.7456, 0.3540],
         [0.3277, 0.5629, 0.3267, 0.7343, 0.6672, 0.4623, 0.4889, 0.4807,
          0.4263, 0.5792],
         [0.3235, 0.6066, 0.4163, 0.5341, 0.2596, 0.6669, 0.4612, 0.4372,
          0.7643, 0.3312],
         [0.5476, 0.3065, 0.3979, 0.4496, 0.4939, 0.6684, 0.3576, 0.5724,
          0.2986, 0.5567]],

        [[0.7605, 0.4339, 0.3442, 0.5792, 0.3153, 0.7892, 0.4327, 0.3710,
          0.6724, 0.5369],
         [0.4321, 0.5861, 0.2328, 0.5398, 0.2913, 0.4234, 0.4183, 0.3687,
          0.6235, 0.5549],
         [0.4624, 0.2525, 0.6226, 0.6313, 0.3271, 0.3057, 0.5653, 0.4519,
          0.5837, 0.3911],
         [0.6031, 0.5530, 0.7344, 0.6788, 0.3344, 0.4077, 0.6090, 0.5592,
          0.5442, 0.2665]]])


In [3]:
#print(r.shape)
import torch.nn as nn
import math

In [4]:
class Attention(nn.Module):
    def __init__(self, D):
        super(Attention, self).__init__()
        self.D, self.attn_weights = D, None
        self.W_q = nn.Linear(D, D)
        self.W_k = nn.Linear(D, D)
    
    def forward(self, query, key, value):
        # query: (B, Lq, D) -> (B, Lq, D), key: (B, Lk, D) -> (B, Lk, D)  
        query, key = self.W_q(query), self.W_k(key)
        # attn_weights: (B, Lq, Lk)
        attn_weights = torch.matmul(query, torch.transpose(key, 2, 1))/math.sqrt(self.D)
        # attn_weights: (B, Lq, Lk)
        attn_weights = nn.functional.softmax(attn_weights, dim=-1)
        # attn_weights: (B, Lq, Lk), value: (B, Lk=Lv, D) -> attn_out: (B, Lq, D)
        attn_out = torch.matmul(attn_weights, value)
        self.attn_weights = attn_weights
        return attn_out

In [5]:
# https://discuss.pytorch.org/t/how-does-one-perform-matrix-multiplication-on-its-transpose-in-a-batch/63281
class BoundaryUnit(nn.Module):
    def __init__(self, D):
        super(BoundaryUnit, self).__init__()
        self.D = D
        self.attn_layer = Attention(D)
    
    def forward(self, f_b, f_w, f_s, f_m):
        # f_b: (B, L, D), f_w: (B, Nq, D) -> f_baq: (B, L, D)
        f_baq = self.attn_layer(f_b, f_w, f_w)
        # f_b: (B, L, D), f_s: (B, D), f_baq: (B, L, D) -> f_bq: (B, L, D)
        f_bq = f_b*(f_baq + torch.unsqueeze(f_s, 1))
        # f_bq: (B, L, D) -> A_b: (B, L, L) 
        # is matmul same as bmm?
        A_b = torch.bmm(f_bq, torch.permute(f_bq, (0, 2, 1)))/math.sqrt(D)
        # A_b: (B, L, L) -> A_b: (B, L, L) 
        A_b = nn.functional.softmax(A_b, dim=-1)
        # A_b: (B, L, L), f_b: (B, L, D) -> f_bb: (B, L, D)
        f_bb = torch.matmul(A_b, f_b)
        # f_m: (B, L, L, D), f_s: (B, D) -> g_m: (B, L, L, D)
        g_m = nn.functional.sigmoid(f_m * torch.unsqueeze(torch.unsqueeze(f_s, 1), 2))
        # A_b: (B, L, L), f_m: (B, L, L, D) -> f_bm: (B, L, D) 
        # I am not confident about the below line.
        f_bm = torch.sum(torch.unsqueeze(A_b, 3) * (g_m*f_m), dim=1)
        return f_bb + f_b + f_bm

In [6]:
B, T, L, C, D, Nq = 2, 16, 4, 4, 10, 8
f_w, f_s = torch.rand(B, Nq, D), torch.rand(B, D)
f_b, f_m = torch.rand(B, L, D), torch.rand(B, L, L, D)

NameError: name 'torch' is not defined

In [7]:
bu = BoundaryUnit(D)

In [8]:
bu.forward(f_b, f_w, f_s, f_m)

NameError: name 'f_b' is not defined

In [38]:
bu.forward(f_b, f_w, f_s, f_m)

tensor([[[1.2975, 0.5749, 1.7918, 0.6207, 1.0068, 0.9105, 1.8348, 0.7117,
          0.9802, 1.1077],
         [1.5002, 0.9919, 1.9060, 1.2438, 1.7170, 1.5226, 2.1005, 1.5808,
          1.8495, 1.4004],
         [1.9210, 0.6964, 2.1388, 1.1725, 1.1931, 1.6444, 1.2248, 1.0414,
          1.9180, 0.7323],
         [0.9838, 0.8306, 1.5939, 0.9571, 0.4915, 1.7980, 1.2398, 0.8132,
          1.3781, 1.6771]],

        [[1.4170, 1.4007, 1.1880, 0.7724, 1.6639, 1.5193, 0.6317, 1.4414,
          1.6333, 0.5223],
         [1.8279, 0.8937, 0.5205, 1.4135, 1.3148, 1.2707, 0.8500, 1.3554,
          0.8522, 0.6273],
         [1.4371, 1.4820, 0.4655, 1.1681, 1.7276, 1.7143, 0.4447, 1.1766,
          0.9938, 0.4931],
         [1.6793, 1.7856, 1.5907, 0.7827, 1.2123, 1.7398, 1.4871, 1.5734,
          1.1277, 0.9093]]], grad_fn=<AddBackward0>)

In [13]:
class ContentAttention(nn.Module):
    def __init__(self, D):
        super(ContentAttention, self).__init__()
        self.D, self.attn_weights = D, None
        self.W_q = nn.Linear(D, D)
        self.W_k = nn.Linear(D, D)
    
    def forward(self, query, key, value):
        # query: (B, L, L, C, D) -> (B, L, L, C, D), key: (B, Nq, D) -> (B, 1, 1, Nq, D)
        query, key = self.W_q(query), self.W_k(key).unsqueeze(1).unsqueeze(2)
        # query: (B, L, L, C, D), key: (B, 1, 1, Nq, D) -> attn_weights: (B, L, L, C, Nq)
        attn_weights = torch.matmul(query, torch.transpose(key, 3, 4))/math.sqrt(self.D)
        # attn_weights: (B, L, L, C, Nq)
        attn_weights = nn.functional.softmax(attn_weights, dim=-1)
        # value: (B, Nq, D) -> (B, 1, 1, Nq, D)
        value = value.unsqueeze(1).unsqueeze(2)
        # attn_weights: (B, L, L, C, Nq), value: (B, 1, 1, Nq, D) -> attn_out: (B, L, L, C, D)
        attn_out = torch.matmul(attn_weights, value)
        self.attn_weights = attn_weights
        return attn_out

In [143]:
class ContentUnit(nn.Module):
    def __init__(self, D):
        super(ContentUnit, self).__init__()
        self.D = D
        self.attn_layer = ContentAttention(D)
    
    def forward(self, f_c, f_w, f_s, f_m):
        # f_c: (B, L, L, C, D), f_w: (B, Nq, D) -> f_caq: (B, L, L, C, D)
        f_caq = self.attn_layer(f_c, f_w, f_w)
        # f_c: (B, L, L, C, D), f_s: (B, D), f_caq: (B, L, L, C, D) -> f_cq: (B, L, L, C, D)
        f_cq = f_c*(f_caq + f_s.unsqueeze(1).unsqueeze(2).unsqueeze(3))
        # f_cq: (B, L, L, C, D) -> A_c: (B, L, L, C, C)
        A_c = torch.matmul(f_cq, torch.transpose(f_cq, 3, 4))/math.sqrt(D)
        # A_c: (B, L, L, C, C) -> A_c: (B, L, L, C, C) 
        A_c = nn.functional.softmax(A_c, dim=-1)
        # A_c: (B, L, L, C, C), f_c: (B, L, L, C, D) -> f_cc: (B, L, L, C, D)
        f_cc = torch.matmul(A_c, f_c)
        # f_m: (B, L, L, D), f_s: (B, D) -> g_m: (B, L, L, D)
        g_m = nn.functional.sigmoid(f_m * f_s.unsqueeze(1).unsqueeze(2))
        # g_m: (B, L, L, D), f_m: (B, L, L, D) -> fbar_m: (B, L, L, D)
        fbar_m = g_m*f_m
        return f_cc + f_c + fbar_m.unsqueeze(3)

In [144]:
B, T, L, C, D, Nq = 2, 16, 4, 2, 10, 8
f_w, f_s = torch.rand(B, Nq, D), torch.rand(B, D)
f_c, f_m = torch.rand(B, L, L, C, D), torch.rand(B, L, L, D)

In [145]:
cu = ContentUnit(D)

In [146]:
cu.forward(f_c, f_w, f_s, f_m)

/Users/kamaleshneerasa/Library/Python/3.9/lib/python/site-packages/torch/nn/functional.py:1967: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([[[[[0.5276, 2.0923, 1.5462, 1.0506, 1.6547, 1.7579, 1.0149, 1.4126,
            1.3579, 1.2588],
           [0.8566, 1.8476, 2.2061, 0.5619, 1.9394, 1.2794, 1.8853, 0.9021,
            1.3206, 2.2555]],

          [[1.1999, 1.9901, 1.9439, 1.3844, 1.8535, 1.7024, 0.8167, 0.6030,
            1.4212, 1.1269],
           [1.4262, 1.9792, 1.8370, 1.7068, 2.1504, 1.8101, 0.5824, 0.6906,
            0.6601, 1.4037]],

          [[2.0583, 0.6171, 1.6764, 1.5276, 0.3658, 0.8862, 0.5299, 0.8281,
            1.6096, 2.4758],
           [1.9364, 0.6685, 1.4122, 1.4779, 0.3182, 1.4714, 0.6876, 1.3289,
            1.5953, 2.4443]],

          [[0.9882, 1.1336, 2.0869, 1.1723, 0.8320, 0.7857, 2.0030, 1.5401,
            1.4718, 1.0503],
           [0.6837, 0.8837, 1.5582, 1.4692, 0.4999, 0.7118, 1.1673, 0.6961,
            0.7714, 0.8826]]],


         [[[0.8933, 1.9120, 1.0092, 1.7778, 2.0191, 1.4497, 1.2893, 1.6217,
            1.3406, 1.5779],
           [1.8110, 1.8607, 1.9034, 1.0810, 1

In [14]:
class ContentUnit(nn.Module):
    def __init__(self, D, dl):
        super(ContentUnit, self).__init__()
        self.D = D
        self.dl = dl
        # IS CONOVLUTION THE CORRECT WAY TO REDUCE CHANNELS?
        self.down_conv_layer_c = nn.Conv3d(D, dl, 1)
        self.down_conv_layer_w = nn.Conv1d(D, dl, 1)
        self.down_conv_layer_s = nn.Conv1d(D, dl, 1)
        self.up_conv_layer_c = nn.Conv3d(dl, D, 1)
        self.attn_layer = ContentAttention(dl)
    
    def forward(self, f_c, f_w, f_s, f_m):
        # f_c: (B, L, L, C, D) -> f_c_hat: (B, L, L, C, dl)
        f_c_hat = self.down_conv_layer_c(f_c.permute(0, 4, 1, 2, 3)).permute(0, 2, 3, 4, 1)
        # f_w: (B, Nq, D) -> f_w_hat: (B, Nq, dl)
        f_w_hat = self.down_conv_layer_w(f_w.permute(0, 2, 1)).permute(0, 2, 1)
        # f_s: (B, D) -> f_s_hat: (B, dl)
        f_s_hat = self.down_conv_layer_s(f_s.permute(1, 0)).permute(1, 0)
        # f_c_hat: (B, L, L, C, dl), f_w_hat: (B, Nq, dl) -> f_caq: (B, L, L, C, dl)
        f_caq = self.attn_layer(f_c_hat, f_w_hat, f_w_hat)
        # f_c: (B, L, L, C, dl), f_s_hat: (B, dl), f_caq: (B, L, L, C, dl) -> f_cq: (B, L, L, C, dl)
        f_cq = f_c_hat*(f_caq + f_s_hat.unsqueeze(1).unsqueeze(2).unsqueeze(3))
        # f_cq: (B, L, L, C, dl) -> A_c: (B, L, L, C, C)
        A_c = torch.matmul(f_cq, torch.transpose(f_cq, 3, 4))/math.sqrt(self.dl)
        # A_c: (B, L, L, C, C) -> A_c: (B, L, L, C, C) 
        A_c = nn.functional.softmax(A_c, dim=-1)
        # A_c: (B, L, L, C, C), f_c_hat: (B, L, L, C, dl) -> f_cc_hat: (B, L, L, C, dl)
        f_cc_hat = torch.matmul(A_c, f_c_hat)
        # f_cc_hat: (B, L, L, C, dl) -> f_cc: (B, L, L, C, D)
        f_cc = self.up_conv_layer_c(f_cc_hat.permute(0, 4, 1, 2, 3)).permute(0, 2, 3, 4, 1)
        # f_m: (B, L, L, D), f_s: (B, D) -> g_m: (B, L, L, D)
        g_m = nn.functional.sigmoid(f_m * f_s.unsqueeze(1).unsqueeze(2))
        # g_m: (B, L, L, D), f_m: (B, L, L, D) -> fbar_m: (B, L, L, D)
        fbar_m = g_m*f_m
        return f_cc + f_c + fbar_m.unsqueeze(3)

In [15]:
B, T, L, C, D, dl, Nq = 2, 16, 4, 2, 10, 5, 8
f_w, f_s = torch.rand(B, Nq, D), torch.rand(B, D)
f_c, f_m = torch.rand(B, L, L, C, D), torch.rand(B, L, L, D)

In [16]:
cu = ContentUnit(D, dl)

In [17]:
cu.forward(f_c, f_w, f_s, f_m)

/Users/kamaleshneerasa/Library/Python/3.9/lib/python/site-packages/torch/nn/functional.py:1967: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([[[[[ 1.3502,  0.3553, -0.0771,  0.5746,  0.8791,  1.2023,  0.9937,
             1.9856,  0.6936,  1.0460],
           [ 0.7101,  1.0525,  0.5853,  1.0497,  0.9007,  1.4608,  0.1260,
             1.7010,  0.8362,  1.2000]],

          [[ 0.8438,  0.6621,  0.8990,  1.3087,  0.2504,  1.1715,  0.2664,
             1.5022,  1.0639,  0.7999],
           [ 0.8977,  0.1238,  0.1942,  0.8194,  0.1469,  1.2756,  0.5481,
             1.1857,  0.9684,  0.8863]],

          [[ 0.5613,  1.0607,  0.0819,  1.8381,  0.8871,  1.6314,  0.6477,
             1.2125,  0.6997,  1.0831],
           [ 0.2486,  0.7267,  0.5575,  1.2569,  0.2143,  1.8381,  0.0708,
             1.1773,  1.3203,  0.3531]],

          [[ 1.0041,  0.9514,  0.9334,  0.4689,  0.6091,  1.3763,  0.7345,
             1.2568,  1.5031,  0.7325],
           [ 0.7183,  0.5197,  0.3792,  0.6798,  0.7869,  0.8222,  0.9855,
             1.5914,  0.5844,  0.5466]]],


         [[[ 1.3774, -0.0395,  1.0293,  1.4122,  0.7551,  0.6055,  0.1

In [26]:
out.shape

torch.Size([2, 4, 4, 2, 10])